# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookprofile',
            name='since',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
