# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooks', '0002_auto_20170530_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookprofile',
            old_name='first_name',
            new_name='name',
        ),
    ]
