# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusers',
            name='profession',
            field=models.CharField(choices=[('w', 'Waiter'), ('c', 'Cook'), ('m', 'Manager')], default='n', max_length=1),
        ),
    ]
