# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 11:22
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managers', '0002_auto_20170603_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appusers',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='appusers',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='appusers',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='appusers',
            name='id',
        ),
        migrations.RemoveField(
            model_name='appusers',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='appusers',
            name='password',
        ),
        migrations.RemoveField(
            model_name='appusers',
            name='username',
        ),
        migrations.AddField(
            model_name='appusers',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=2, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
