# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='waiterprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('age', models.CharField(max_length=2)),
                ('birth', models.DateField()),
                ('since', models.DateTimeField(auto_now_add=True)),
                ('adress', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
    ]
