# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiters', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cook',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
