# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waiters', '0004_order_cook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waiters.waiterprofile')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='waiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waiters.waiterprofile'),
        ),
    ]
