# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waiters', '0005_auto_20170604_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiters',
            name='profile',
        ),
        migrations.AlterField(
            model_name='waiterprofile',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='waiters.Waiters'),
        ),
    ]
