# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiters', '0006_auto_20170604_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiterprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
