# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waiters', '0007_auto_20170604_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='waiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waiters.Waiters'),
        ),
    ]
